"""Transcribe the original UNIFAC group tables into src/engthermo/_unifac_data.py.

Subgroup volumes R and surface areas Q and the main-group interaction parameters a_mn (K) are those of the
published UNIFAC tables (Fredenslund, Jones & Prausnitz 1975; revised by Hansen et al., Ind. Eng. Chem. Res. 30,
1991). They are copied programmatically from the open-source `thermo` package (C. Bell; MIT licence), which
transcribes those tables, so that nothing is typed by hand.   pip install thermo; python tools/transcribe_unifac.py
"""
from pathlib import Path

import thermo.unifac as u

lines = ["# Original UNIFAC group parameters (Hansen et al. 1991 revision). Generated by tools/transcribe_unifac.py -",
         "# do not edit by hand.", "", "# subgroup id: (subgroup name, main-group id, main-group name, R, Q)", "SUBGROUPS = {"]
for sid in sorted(u.UFSG):
    s = u.UFSG[sid]
    lines.append(f"    {sid}: ({s.group!r}, {s.main_group_id}, {s.main_group!r}, {s.R!r}, {s.Q!r}),")
lines += ["}", "", "# main-group interaction parameters a_mn in K: INTERACTIONS[m][n]", "INTERACTIONS = {"]
for m in sorted(u.UFIP):
    inner = ", ".join(f"{n}: {u.UFIP[m][n]!r}" for n in sorted(u.UFIP[m]))
    lines.append(f"    {m}: {{{inner}}},")
lines += ["}", ""]
Path(__file__).resolve().parents[1].joinpath("src", "engthermo", "_unifac_data.py").write_text("\n".join(lines))
print(f"wrote {len(u.UFSG)} subgroups and {sum(len(v) for v in u.UFIP.values())} interaction parameters")
