"""Transcribe the IAPWS-IF97 coefficient tables into src/engthermo/_if97_coefficients.py.

The numbers are those of the IAPWS "Revised Release on the IAPWS Industrial Formulation 1997 for the
Thermodynamic Properties of Water and Steam" (2007). They are copied programmatically from the open-source
`iapws` package (J. J. Gómez Romera), which transcribes the release, so that no coefficient is ever typed by
hand; engthermo's validation then checks the implementation against the release's own verification tables.

    pip install iapws
    python tools/transcribe_if97.py
"""
import inspect
import re
from pathlib import Path

import iapws.iapws97 as m

C = m.Const
out = ["# IAPWS-IF97 coefficient tables (IAPWS 2007 revised release). Generated by tools/transcribe_if97.py -",
       "# do not edit by hand. Table numbers refer to the release.", "", "import numpy as np", ""]


def arr(name, values, fmt="%.14e"):
    vals = ", ".join(fmt % v if isinstance(v, float) else str(v) for v in values)
    out.append(f"{name} = np.array([{vals}])")


# Table 2: region 1 (Eq. 7): 34 terms
arr("R1_I", C.Region1_Li, "%d"); arr("R1_J", C.Region1_Lj, "%d"); arr("R1_n", C.Region1_n)
# Tables 10 and 11: region 2 ideal-gas part (Eq. 16, 9 terms) and residual part (Eq. 17, 43 terms)
arr("R2_J0", C.Region2_cp0_Jo, "%d"); arr("R2_n0", C.Region2_cp0_no)
arr("R2_I", C.Region2_Li, "%d"); arr("R2_J", C.Region2_Lj, "%d"); arr("R2_n", C.Region2_n)
# Table 30: region 3 (Eq. 28), 40 terms; n[0] multiplies ln(delta)
arr("R3_I", C.Region3_Li, "%d"); arr("R3_J", C.Region3_Lj, "%d"); arr("R3_n", C.Region3_n)
src3 = inspect.getsource(m._Region3)
R3_n1 = float(re.search(r"\((\d\.\d+) \* log\(d\)\)", src3).group(1))
out.append(f"R3_n1 = {R3_n1!r}          # Table 30, n_1: coefficient of ln(delta)")
# Tables 37 and 38: region 5 (Eqs. 33-34)
arr("R5_J0", C.Region5_cp0_Jo, "%d"); arr("R5_n0", C.Region5_cp0_no)
arr("R5_I", C.Region5_Li, "%d"); arr("R5_J", C.Region5_Lj, "%d"); arr("R5_n", C.Region5_n)
# Table 34: saturation line (Eqs. 30-31), and Table 1: boundary between regions 2 and 3 (Eqs. 5-6)
src = inspect.getsource(m._PSat_T)
nums4 = re.findall(r"[-+]?\d\.\d+E[-+]\d+", src.split("n = (")[1].split(")")[0])
arr("R4_n", [float(x) for x in nums4])
src = inspect.getsource(m._P23_T)
nums = re.findall(r"[-+]?\d\.\d+e[-+]?\d+", src.split("n = (")[1].split(")")[0])
arr("B23_n", [float(x) for x in nums])
Path(__file__).resolve().parents[1].joinpath("src", "engthermo", "_if97_coefficients.py").write_text("\n".join(out) + "\n")
print("wrote _if97_coefficients.py:", {k: len(v) for k, v in
      [("R1", C.Region1_n), ("R2 ideal", C.Region2_cp0_no), ("R2 residual", C.Region2_n), ("R3", C.Region3_n),
       ("R5 ideal", C.Region5_cp0_no), ("R5 residual", C.Region5_n), ("R4", nums4), ("B23", nums)]}, "R3 n1 =", R3_n1)
